### ISSUE TITLE
Is it a trojan or virus?

### ISSUE THREAD

**Issue by MarkusZiegler** [idkosilov/NDICapture#1]
When downloading the file I got a warning.
Possible threat.
I checked with virustotal.com and gut several warnings.
Can you tell me more about this?
Markus
![2023-05-04 (2)](https://user-images.githubusercontent.com/18186674/236220775-8adb9684-3cc2-408f-91c8-2fddcc733b2e.png)

**Comment by idkosilov** [comment]
Hello. The binary file is not signed.  For this reason, Windows complains about viruses.  You can check the source code for viruses and build the program yourself.  I'll update the build instructions later.  In any case, you can safely use the current binary, there are no viruses.
